### ISSUE TITLE
Bad link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Honestpuck** [dan-snelson/Setup-Your-Mac#104]
In section 4 of the CONTRIBUTING.md is a link meant to go to "Remote Validation" - `https://github.com/dan-snelson/Setup-Your-Mac/blob/Validations/README.md`

Click on it and you get a 404 page "The main branch of Setup-Your-Mac does not contain the path 
CONTRIBUTING.md."

This seems strange as you can see CONTRIBUTING.md right there in the file list of the main branch.

Nevertheless the correct link would seem to be `https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Validations/README.md`

**Comment by dan-snelson** [comment]
Thanks, Tony!
