### ISSUE TITLE
Customisation for configurations

### ISSUE THREAD

**Issue by alexfinn** [dan-snelson/Setup-Your-Mac#110]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a feature that would be handy for certain builds.
The ability to have "overlayicon" and "bannerimage" be customisable per configuration.
So if configuration 1, then overlayicon1 and bannerimage1.
I cant see a way to currently do this with the way _Setup Your Mac" dialog Settings and Features_ is currently set up.

**Describe the solution you'd like**
Ideally, have "bannerimage" and "overlayicon" look at a an extra line that would have a customisable location

**Describe alternatives you've considered**
I've tried to do this myself, but I cant see how i can do it efficiently and cleanly. Thanks!

**Comment by dan-snelson** [comment]
Thanks, @alexfinn.

(See [thread](https://macadmins.slack.com/archives/C04FRRN3281/p1695035064460739).)

**Comment by dan-snelson** [comment]
@drtaru: Sounds like you’ve already got this worked out in you’re head …

**Comment by dan-snelson** [comment]
Addressed in [`1.13.0`](https://github.com/dan-snelson/Setup-Your-Mac/releases/tag/v1.13.0).

Thank you!
