### ISSUE TITLE
/var/log/com.setupyourmac - additional debugging

### ISSUE THREAD

**Issue by clevelandbread** [dan-snelson/Setup-Your-Mac#119]
**Is your feature request related to a problem? Please describe.**

I am frustrated when a computer does not have enough storage space to complete the enrollment process and the logs would not provide that information when completing the trigger of a policy.

**Describe the solution you'd like**

I would like a little bit more debugging in the logs, I know it's rare but it might come useful as time goes on. Specifically, I would like debugging to include the explanation if there is not enough storage to complete the installation of the targeted application(s).

**Additional context**

**Comment by dan-snelson** [comment]
Thanks for the FR, @clevelandbread. 

Please help me understand:
1. Are you enrolling personally owned Macs which already have nearly full drives?
2. Are the logs not be saved at all?

(We’re only enrolling organizationally owned devices, fresh out-of-box, so we never worry about available disk space.)

Please see the disk usage info in: [B. Dynamic Download Estimates](https://snelson.us/2023/08/setup-your-mac-1-12-1/#B)

**Comment by clevelandbread** [comment]
1.  Enrolling virtual machines with set drive capacity.
2. The logs are logging as normal, but it was not giving the reason of failure due to low disk space.

**Comment by dan-snelson** [comment]
Thanks for the additional details. 

My recommendation is to allocate enough space to your VM to accommodate what you’re trying to install. 

Closing as not planned.
