### ISSUE TITLE
Configuration:catch-all info showing in UI dialog unnecessary 

### ISSUE THREAD

**Issue by mani2care** [dan-snelson/Setup-Your-Mac#12]
Below info is unnecessary showing in dialog UI when in production model.

Configuration:catch-all ('welcome' dialog disable)
Configuration:catch-all (video)

![A321443B-CE24-4D16-9B63-6458AAA845B6](https://user-images.githubusercontent.com/52978899/224962096-12c26a55-e178-4c69-b314-32f2a2998e4b.jpeg)

**Comment by dan-snelson** [comment]
Thanks for the heads-up, @mani2care!

This _should_ be resolved in [1.8.2-rc2](https://github.com/dan-snelson/Setup-Your-Mac/blob/development/Setup-Your-Mac-via-Dialog.bash).

Please test and advise.

**Comment by dan-snelson** [comment]
<img width="932" alt="Screenshot 2023-03-14 at 2 41 12 AM" src="https://user-images.githubusercontent.com/24623109/224964971-b264870e-b100-4b36-af1a-695bbd26412b.png">

<img width="932" alt="Screenshot 2023-03-14 at 2 39 04 AM" src="https://user-images.githubusercontent.com/24623109/224964994-b1f6c497-9de6-466b-81a1-0ede37f50de1.png">

**Comment by mani2care** [comment]
Thanks @dan-snelson  issue resolve with this new version 
![Uploading 9EC7D454-F686-4F25-8790-82C159B3AE0E.jpeg…]()

**Comment by dan-snelson** [comment]
Addressed in `1.9.0`.
