### ISSUE TITLE
Recon option for "Position" field

### ISSUE THREAD

**Issue by astrugatch** [dan-snelson/Setup-Your-Mac#120]
> **Note:** While all requests are welcome, finding available cycles to custom-code a feature we won't use in our production environment is always challenging.

**Is your feature request related to a problem? Please describe.**
Moving from DEP notify, want to utilize the "Position" field in Jamf for some specific situations that we previously used extension attributes and API calls for.

**Describe the solution you'd like**
Just like with User, Building, Dept etc. I want to have a drop down list of positions that will fill on recon up to the JSS (as opposed to our DEPNotify workflow that updates an extension attribute with API calls)

**Comment by dan-snelson** [comment]
@astrugatch: Will you please give @drtaru's update to [`1.13.0-rc4`](https://github.com/dan-snelson/Setup-Your-Mac/blob/1.13.0/Setup-Your-Mac-via-Dialog.bash) a spin?

**Comment by astrugatch** [comment]
Absolutely. I’ll spin up a test first thing in the morning. Already set a reminder.

**Comment by astrugatch** [comment]
Tested as working.

Just for my edification does the recon for the items in the dialog happen before the policies start to run on the next screen?

**Comment by dan-snelson** [comment]
Thanks for confirming, @astrugatch.

No; you’ll need to include `recon` in your `policyJSON` at least once:
https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L1035-L1045

See: [`Recon` Validation](https://snelson.us/2023/08/setup-your-mac-1-12-1/#recon-validation).

**Comment by dan-snelson** [comment]
Addressed in [`1.13.0`](https://github.com/dan-snelson/Setup-Your-Mac/releases/tag/v1.13.0).

Thank you!
