### ISSUE TITLE
Additional Completion Screen/Message

### ISSUE THREAD

**Issue by tonyyo11** [dan-snelson/Setup-Your-Mac#125]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem, but rather just user experience enhancements

**Describe the solution you'd like**
For a successful build, it would be nice to have SYM flip to a final screen with custom messaging informing the user that a build has been successful. Presently, SYM have a status message at the bottom notifying the user that the build has been completed, and then they may interact with he completion button (wait/exit/restart/etc). Instead, SYM should show a final page, void of the policy array list, with final messaging to the user. This will give admins the ability to add additional messaging such as "You must restart your system to enable XYZ." or something as simple as "Thank you for completing the build, for additional resources, please go to ABC or Self Service"

**Describe alternatives you've considered**
I thought of simply calling a brand new Dialog window, but then I'd run the risk of having it pop up even when there are policy failures, so dropped that idea. 

**Additional context**
Full Disclosure - a colleague asked me if there were additional completion options for SYM as we work. After typing up this ticket I realized that I'm essentially asking for a copy of Jamf's macOS Onboarding Setup Complete Screen....
![Screenshot 2023-11-29 at 12 58 42 PM](https://github.com/dan-snelson/Setup-Your-Mac/assets/41205894/6dc17517-1bcf-4569-b875-38635fcf4e10)

**Comment by dan-snelson** [comment]
Thanks for the FR, @tonyyo11

**Comment by dan-snelson** [comment]
Thanks, @drtaru, for pointing out [Removing a list](https://github.com/swiftDialog/swiftDialog/wiki/Item-Lists#removing-a-list).

**Comment by tonyyo11** [comment]
That's it! Thanks. This is closed. 
Edited the script beginning at `line 2025` of version 12.7 and was able to do exactly what I wanted to accomplish.
Added two new lines, one with `dialogUpdateSetupYourMac "list: hide"` and another with `dialogUpdateSetupYourMac "message: <message>"`
