### ISSUE TITLE
Feature Request: "Installed" vs. "Previously Installed"

### ISSUE THREAD

**Issue by dan-snelson** [dan-snelson/Setup-Your-Mac#13]
(From @Manikandan in the [#setup-your-mac](https://macadmins.slack.com/archives/C04FRRN3281/p1678793236350789?thread_ts=1678782755.290789&cid=C04FRRN3281) Channel of the Mac Admins Slack.)

**Feature Request:** Previously installed apps with a `filepath` validation should display "Previously Installed" (instead of a generic "Installed").

**Comment by dan-snelson** [comment]
@manikandan:

Presuming this is what you asked for, please test-drive [1.8.2-rc3](https://github.com/dan-snelson/Setup-Your-Mac/blob/development/Setup-Your-Mac-via-Dialog.bash).

<img width="932" alt="Screenshot 2023-03-14 at 7 08 29 PM" src="https://user-images.githubusercontent.com/24623109/225179978-9c839a1c-fae9-49af-ba1c-823caa9e63a4.png">

**Comment by dan-snelson** [comment]
> You think you got the stuff it takes to break away?
> Boy, you'll be on the track every day!
> Talent, vigor, drive …
> … you'll eat peanut butter the rest of your life!

[Trou Macacq](https://youtu.be/dQw4w9WgXcQ?t=44) by Squirrel Nut Zippers

**Comment by mani2care** [comment]
Hi Dan it’s working very well with the new changes 
![9CC39D8A-E593-4A5A-9F12-8D9B97C53A58](https://user-images.githubusercontent.com/52978899/225344004-b4301efe-c37c-4aed-a323-bf0d766a1431.jpeg)

**Comment by dan-snelson** [comment]
Addressed in `1.9.0`.
