### ISSUE TITLE
FR: Add Configuration to the help (?) button output for help

### ISSUE THREAD

**Issue by master-vodawagner** [dan-snelson/Setup-Your-Mac#17]
> **Note:** While all requests are welcome, finding available cycles to custom-code a feature we won't use in our production environment is always challenging.

**Is your feature request related to a problem? Please describe.**
No, just extends an existing feature

**Describe the solution you'd like**
Hey @dan-snelson

Just a simple FR I believe, would be good to add the chosen configuration to the help ? button which offers the computer information

**Describe alternatives you've considered**
None

**Additional context**

**Comment by dan-snelson** [comment]
Great idea!

**Comment by dan-snelson** [comment]
@master-vodawagner:

Looks like this will have to wait for a possible update to swiftDialog; see [swiftDialog Issue No. 248](https://github.com/bartreardon/swiftDialog/issues/248).

```
# New code, starting around Line No. 2267

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Update Setup Your Mac's helpmessage
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Output Line Number in `verbose` Debug Mode
if [[ "${debugMode}" == "verbose" ]]; then updateScriptLog "# # # SETUP YOUR MAC VERBOSE DEBUG MODE: Line No. ${LINENO} # # #" ; fi

if [[ -n ${infoboxConfiguration} ]]; then

    updateScriptLog "Update 'helpmessage' with Configuration: ${infoboxConfiguration} …"

    helpmessage="If you need assistance, please contact the Global Service Department:  \n- **Telephone:** +1 (801) 555-1212  \n- **Email:** support@domain.org  \n- **Knowledge Base Article:** KB0057050  \n\n**Configuration:** \n- ${infoboxConfiguration}  \n\n**Computer Information:**  \n- **Operating System:**  ${macOSproductVersion} (${macOSbuildVersion})  \n- **Serial Number:** ${serialNumber}  \n- **Dialog:** ${dialogVersion}  \n- **Started:** ${timestamp}"
    
fi

dialogUpdateSetupYourMac "helpmessage: ${helpmessage}"
```

**Comment by dan-snelson** [comment]
@master-vodawagner: 

This has been added to [`1.10.0-rc13`](https://github.com/dan-snelson/Setup-Your-Mac/blob/development/Setup-Your-Mac-via-Dialog.bash#L2551-L2569) (and _requires_ `swiftDialog v2.2`).

**Comment by dan-snelson** [comment]
Thanks, @master-vodawagner!
