### ISSUE TITLE
Disable Mission Control to prevent users exiting SYM

### ISSUE THREAD

**Issue by remcoverburgh** [dan-snelson/Setup-Your-Mac#18]
> **Note:** While all requests are welcome, finding available cycles to custom-code a feature we won't use in our production environment is always challenging.

**Is your feature request related to a problem? Please describe.**
A clear, concise description of the problem. (i.e., I'm frustrated when ...)

Disable Mission Control to prevent users exiting SYM

**Describe the solution you'd like**
A clear, concise description of what you want to happen.

An option to toggle of or on the option for Mission Control.

**Describe alternatives you've considered**
A clear, concise description of any alternative solutions or features you've considered.

**Additional context**

simple commands like the following could do the trick.

"defaults write com.apple.dock mcx-expose-disabled -bool TRUE && killall Dock"
"defaults delete com.apple.dock mcx-expose-disabled && killall Dock"

maybe like this part of the current script.
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Temporarily disable `jamf` binary check-in (thanks, @mactroll and @cube!)
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

**Comment by dan-snelson** [comment]
Thanks, @remcoverburgh!

**Comment by dan-snelson** [comment]
Here's a link to the [#setup-your-mac Channel Conversation](https://macadmins.slack.com/archives/C04FRRN3281/p1680179463588509).

**Comment by dan-snelson** [comment]
@remcoverburgh:

I looking at this today, my current understanding is that it's **not** possible to disable Mission Control in SYM; see [Feature Request: Disable Mission Control when using blurscreen #198](https://github.com/bartreardon/swiftDialog/issues/198).

If you can find out how to pull it off, I'd be happy to add it to SYM.

Please advise. Thanks.

**Comment by dan-snelson** [comment]
@remcoverburgh:

Without additional information about the feasibility of this Feature Request, when `1.10.0` is "official," I'll mark this "Closed as not planned."

Thanks.

**Comment by dan-snelson** [comment]
Thanks for the link, @robjschroeder:

https://amsys.co.uk/how-to-disable-mission-control-and-spaces-in-os-x

**Comment by dan-snelson** [comment]
@robjschroeder:

Unfortunately, these are the same commands @remcoverburgh initially provided, which, in a single test on physical hardware with macOS 13.3.1, no longer appear to disable Mission Control.
