### ISSUE TITLE
Bug Report: Add additional check for ${loggedInUser}

### ISSUE THREAD

**Issue by robjschroeder** [dan-snelson/Setup-Your-Mac#2]
Please add an additional check to populate the ${loggedInUser} variable before the script looks to see if the variable exists. This will ensure that before the check, a recent variable check has been completed. Thank you!

loggedInUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }' )

https://github.com/dan-snelson/Setup-Your-Mac/blob/f195cb4ad5b9727aaf2455d320e9049a5556ea77/Setup-Your-Mac-via-Dialog.bash#L188

**Comment by dan-snelson** [comment]
Thanks, Obi-@robjschroeder!

**Comment by dan-snelson** [comment]
@robjschroeder: I'm seeing `loggedInUser` defined at [Line 51](https://github.com/dan-snelson/Setup-Your-Mac/blob/f195cb4ad5b9727aaf2455d320e9049a5556ea77/Setup-Your-Mac-via-Dialog.bash#L51); what am I missing?

**Comment by dan-snelson** [comment]
Please advise the steps to reproduce. Thanks.

**Comment by robjschroeder** [comment]
When using an Automated Device Enrollment workflow and SYM, it looks like the $loggedInUser variable is not getting populated when the script first checks on line 51, so when the script checks for the variable to be populated and not loginwindow on line 189, SYM thinks there is no loggedInUser because the variable is blank. With the additional chance for the $loggedInUser variable to be populated right before it decides to continue or exit, you have at that moment a chance to grab the correct variable, whether it is truly blank or if there is a logged In user. 

This issue only seems to affect those using SYM and ADE workflows on versions 1.7.2 +

**Comment by dan-snelson** [comment]
Please see: https://github.com/dan-snelson/dialog-scripts/issues/41

**Comment by dan-snelson** [comment]
@robjschroeder:

Please test-drive [1.8.1-rc1](https://github.com/dan-snelson/Setup-Your-Mac/commit/84425a7cefc35432fb684f9ec5a4b886a4a17b0b); I'd be interested to see the client-side logs.

Thanks.

**Comment by dan-snelson** [comment]
Thanks, @robjschroeder.

Addressed in [1.8.1](https://github.com/dan-snelson/Setup-Your-Mac/releases/tag/v1.8.1).
