### ISSUE TITLE
Limit the 'loggedInUserFirstname' variable to 25 characters and capitalize its first letter

### ISSUE THREAD

**Issue by mani2care** [dan-snelson/Setup-Your-Mac#20]
Hi Dan,

Greetings for the better visibility and standardising the login user first letter to making it capitalising 

from : https://github.com/dan-snelson/Setup-Your-Mac/blob/5c0c95887aa7cb82c7c20010b312710341395a9d/Setup-Your-Mac-via-Dialog.bash#L216

to : 
`loggedInUserFullname=$( id -F "${loggedInUser}" | awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)), $i)}1')`

Find the attached out put before : 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/52978899/229426344-f95f2f03-149a-41ef-a940-140275e1db3d.png">

Find the out put after : 

<img width="484" alt="image" src="https://user-images.githubusercontent.com/52978899/229426407-5767dba1-5918-436f-b6ee-373c5b1ef041.png">

**Comment by dan-snelson** [comment]
Thanks for the ongoing testing and FRs, @mani2care.

While this strikes me as a "garbage in, garbage out" situation — if users are too lazy to capitalize their own names, why should we reward their bad behavior —  please test the following:

`loggedInUserFirstname=$( echo "$loggedInUserFullname" | sed -E 's/^.*, // ; s/([^ ]*).*/\1/' | awk '{print toupper(substr($0,1,1))substr($0,2)}' )`

<img width="288" alt="Screenshot 2023-04-03 at 2 15 02 AM" src="https://user-images.githubusercontent.com/24623109/229543910-6be9f4de-96d1-4aad-99ff-967352770b98.png">

<img width="932" alt="Screenshot 2023-04-03 at 2 16 03 AM" src="https://user-images.githubusercontent.com/24623109/229543979-aee7edf3-7d00-47be-8d57-ff2a80c1803a.png">

**Comment by mani2care** [comment]
hi Dan,

Tested with this loggedInUserFirstname its works well.
`loggedInUserFirstname=$( echo "$loggedInUserFullname" | sed -E 's/^.*, // ; s/([^ ]*).*/\1/' | awk '{print toupper(substr($0,1,1))substr($0,2)}' )`

However, if the account name is very long then 15, its another scenario. for example 
Raju Manikandanrajusubbaramanigoundar
Alexandros Constantinou
Anastasia Papadopoulos
Christophoros Georgiou
Demetrios Anastasiades
Eleni Ioannou-Kyprianou
Georgios Michalopoulos
Katerina Tzortzis-Papadakis
Konstantinos Papageorgiou
Margarita Kyprianou-Christodoulou
Panayiotis Papageorgopoulos

can be possible like this if the name is very longer just to limiting the letters 10  

```
loggedInUserFullname=$( id -F "${loggedInUser}" )
loggedInUserFirstname=$( echo "$loggedInUserFullname" | sed -E 's/^.*, // ; s/([^ ]*).*/\1/' | cut -c 1-10 | awk '{print toupper(substr($0,1,1))substr($0,2)}' )
if [ ${#loggedInUserFullname} -gt 11 ]; then
  loggedInUserFirstname="${loggedInUserFirstname}..."
fi
```

Manikandan......   so this will be limited printing the letters after if any words will be printed like ......
so this will help us to reducing the over size the table.

Before : 

<img width="1680" alt="Screenshot 2023-04-04 at 1 32 49 PM" src="https://user-images.githubusercontent.com/52978899/229730404-b38cbfb7-64b6-4d53-aa42-36512ff87aac.png">

After :

<img width="1680" alt="Screenshot 2023-04-04 at 1 33 10 PM" src="https://user-images.githubusercontent.com/52978899/229730813-c8cda936-7a53-46d0-bf58-00898eca01fa.png">

**Comment by dan-snelson** [comment]
@mani2care:

Thanks for the additional details and example strings.

Please test the following:

`loggedInUserFirstname=$( echo "$loggedInUserFullname" | sed -E 's/^.*, // ; s/([^ ]*).*/\1/' | sed 's/\(.\{15\}\).*/\1.../' | awk '{print toupper(substr($0,1,1))substr($0,2)}' )`

```
❯ loggedInUserFullname="raju, manikandanrajusubbaramanigoundar"
❯ loggedInUserFirstname=$( echo "$loggedInUserFullname" | sed -E 's/^.*, // ; s/([^ ]*).*/\1/' | sed 's/\(.\{15\}\).*/\1.../' | awk '{print toupper(substr($0,1,1))substr($0,2)}' )
❯ echo $loggedInUserFirstname
Manikandanrajus...
```

**Comment by dan-snelson** [comment]
@mani2care: The example above is for the first `15` characters; please advise if you'd prefer the first `10` characters (as in your example).

**Comment by mani2care** [comment]
I think this is looks good shot and sweet ,

```
#!/bin/bash
loggedInUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }' )
loggedInUserFullname=$( id -F "${loggedInUser}" )
loggedInUserFirstname=$( echo "$loggedInUserFullname" | sed -E 's/^.*, // ; s/([^ ]*).*/\1/' | sed 's/\(.\{15\}\).*/\1.../' | awk '{print toupper(substr($0,1,1))substr($0,2)}' )
echo loggedInUserFullname : $loggedInUserFullname
echo loggedInUserFirstname: $loggedInUserFirstname
```

Find the test results:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/52978899/229865260-8b385b97-af09-44df-9b47-4d0d4eb8847e.png">

**Comment by dan-snelson** [comment]
@mani2care: This _should_ be addressed in [`1.10.0-rc1`](https://github.com/dan-snelson/Setup-Your-Mac/blob/development/Setup-Your-Mac-via-Dialog.bash#L213).

**Comment by dan-snelson** [comment]
@mani2care: Please test-drive [`1.10.0-rc2`](https://github.com/dan-snelson/Setup-Your-Mac/blob/development/Setup-Your-Mac-via-Dialog.bash).

As mentioned in the #setup-your-mac Channel on the Mac Admins Slack:

> Long-term, I feel that if upgrading to the latest version of SYM is [well-documented](https://github.com/dan-snelson/Setup-Your-Mac/issues/6#issuecomment-1480097767), Mac Admins can roll-their-own customizations now and easily maintain them across versions, without adversely impacting the entire user-base.

**Comment by dan-snelson** [comment]
(You can uncomment [Line No. 216 ](https://github.com/dan-snelson/Setup-Your-Mac/blob/development/Setup-Your-Mac-via-Dialog.bash#L216) during testing.)

**Comment by mani2care** [comment]
Hi @dan-snelson find the attached the test results.


https://user-images.githubusercontent.com/52978899/230109441-d3270a54-8d37-456a-82aa-2d434a119029.mov


https://user-images.githubusercontent.com/52978899/230109690-f642b9a1-1cd8-417c-8e60-cc447f094c5a.mov

**Comment by mani2care** [comment]
One more request change the headline to Center align so it’s looks good

**Comment by dan-snelson** [comment]
@mani2care: This one comes down to personal preference; I think the left-aligned header looks good.

**Comment by dan-snelson** [comment]
Thanks, @mani2care!
