### ISSUE TITLE
Don't show the failure screen after SYM has run.

### ISSUE THREAD

**Issue by DevliegereM** [dan-snelson/Setup-Your-Mac#25]
> **Note:** While all requests are welcome, finding available cycles to custom-code a feature we won't use in our production environment is always challenging.

**Is your feature request related to a problem? Please describe.**
Not a problem, just something that would be nice to have.

**Describe the solution you'd like**
A variable to not let the failure dialog pop up. Standard it should still pop-up but having the ability to turn it off would be nice to have. 

**Describe alternatives you've considered**
I tried tinkering myself a bit but writing extensions in someone else's code is not the same 😄

**Comment by dan-snelson** [comment]
Thanks, Michiel!

**Comment by dan-snelson** [comment]
@DevliegereM:

What would you like to happen if there **are** failures reported in the main SYM dialog, but the so-called "Failure" dialog has been disabled?

**Comment by dan-snelson** [comment]
@DevliegereM:

Please test-drive `1.10.0-rc14` (in the [development](https://github.com/dan-snelson/Setup-Your-Mac/blob/development/Setup-Your-Mac-via-Dialog.bash) branch) by setting [`failureDialog`](https://github.com/dan-snelson/Setup-Your-Mac/blob/development/Setup-Your-Mac-via-Dialog.bash#L68) to `false`.

**Comment by DevliegereM** [comment]
> @DevliegereM:
> 
> What would you like to happen if there **are** failures reported in the main SYM dialog, but the so-called "Failure" dialog has been disabled?

I would like it to be sent to the .log file (which already happens) so that works fine for me. Users are already rebooted after SYM completes so the recurring check-in for missing items will happen when they log in.

**Comment by dan-snelson** [comment]
Thanks, @DevliegereM!
