### ISSUE TITLE
Add function to send details to MS Teams Channel

### ISSUE THREAD

**Issue by robjschroeder** [dan-snelson/Setup-Your-Mac#27]
> **Note:** While all requests are welcome, finding available cycles to custom-code a feature we won't use in our production environment is always challenging.

**Is your feature request related to a problem? Please describe.**
FR is not related to a problem

**Describe the solution you'd like**
Ability to send message to MS Teams for failures and completions

**Describe alternatives you've considered**
This FR will include integration with MS Teams, but would be able to be modified to use Slack, etc..

**Additional context**

**Comment by dan-snelson** [comment]
Thanks, @robjschroeder; please advise if **you're** planning a PR for this.

**Comment by robjschroeder** [comment]
Opened PR #29

**Comment by dan-snelson** [comment]
Thanks, @robjschroeder!
