### ISSUE TITLE
Troubleshooting Infos get not displayed in RC 1.10.0-rc18 / script hangs

### ISSUE THREAD

**Issue by colorenz** [dan-snelson/Setup-Your-Mac#33]
The troubleshooting infos get not displayed in RC 1.10.0-rc18 the scripts hangs on the [wait](https://github.com/dan-snelson/Setup-Your-Mac/blob/development/Setup-Your-Mac-via-Dialog.bash#L1462) and does not go further. You can test it with the test.txt i have attached.
I have only changed the validation from Globalprotect to generate a failure.

I tested with the following Parameters.

![image](https://user-images.githubusercontent.com/16665557/233846834-2f9958c8-28fe-461f-8bb4-d23b3ca2d6de.png)
[test.txt](https://github.com/dan-snelson/Setup-Your-Mac/files/11304015/test.txt)

Best Regards

colorenz

**Comment by robjschroeder** [comment]
I am seeing the same thing. I commented out the `wait` and dialog went straight to failure dialog, then hung on the next wait when the failure details were presented. It does not seem like the button is taking the dialog past the wait.

**Comment by colorenz** [comment]
I did some more digging, I used jobs to show me the processes that are still running before the wait. It seems to be the caffeinate process is the problem.

![image](https://user-images.githubusercontent.com/16665557/233856829-d7509f47-79e6-4782-ad68-e6299dcccccf.png)

**Comment by colorenz** [comment]
Okay tested to much.... I had 30 caffeinate  processes open....

sudo killall caffeinate fixed the problem 👯  .... Or next time reboot...
