### ISSUE TITLE
Flexible JSON Input file

### ISSUE THREAD

**Issue by delize** [dan-snelson/Setup-Your-Mac#39]
**Is your feature request related to a problem? Please describe.**
Currently, to make modifications for some variables or the script itself, you have to rewrite a massive context of the script to use for customized personal use.

Because the update process requires (at the moment at least) diffing the version releases and copy and pasting update commits (or looking through Github History, it would be nice if a file could be used as an input value and be used in place of the existing defaults in your script (EG: Welcome prompt, Package requirements, etc). 

For values that are not included in the json file, they can either take one of two options:
1. Ignore the unset variables
2. Use the existing variables in the script
This could be a toggle option either via the script itself or the JSON input file.

**Describe the solution you'd like**
Create a variable that takes a  json or .env file that can be used as an import/read from file to allow for a flexible update path to sym.sh

**Describe alternatives you've considered**
Diffing git commits or files to see what has changed

**Comment by delize** [comment]
See this Slack thread as a prime example...
https://macadmins.slack.com/archives/C04FRRN3281/p1682428258579769

**Comment by dan-snelson** [comment]
Thanks, @delize!

**Comment by dan-snelson** [comment]
https://github.com/dan-snelson/Setup-Your-Mac/issues/6#issuecomment-1480097767

**Comment by dan-snelson** [comment]
@delize:

Do the recent changes in SYM `1.10.0` meet your needs for this FR?

**Comment by dan-snelson** [comment]
@delize:

I'll go ahead and close this as completed; if SYM `1.10.0` doesn't meet your need, please feel free to re-open.

Thanks.
