### ISSUE TITLE
Have to 2 separate ComputerNames for 2 separate regions in our Company

### ISSUE THREAD

**Issue by midiman1000** [dan-snelson/Setup-Your-Mac#5]
Love the work....BTW.
I've configured the regex Computer Name at enrollment and is very strict so EU's do not get this wrong.
Works perfectly...!
Turns out that one region of the company has a different naming convention for their Macs.
Is it possible to have two regex entries or should I add the scutil commands later in the script with some if logic and run it from there.
Just a thought.

Much appreciated and thank you.

**Comment by GadgetGeekNI** [comment]
Would it be easier to automatically generate the computer name based on an Office selection dropdown and have an if else for the regex statement in line to ensure that office 1 gets regex 1 and office 2 gets regex 2?

**Comment by dan-snelson** [comment]
@midiman1000:

Thanks for opening an issue and for sharing your use-case.

After counseling with another respected Mac Admin, I'm going to close this issue as "not planned" and invite you to review the [Support](https://snelson.us/2023/03/setup-your-mac-1-8-0-via-swiftdialog/#support) information for SYM.

**Comment by dan-snelson** [comment]
(Internally, we’re using Pico’s [get_marketing_model_name.sh](https://github.com/freegeek-pdx/macOS-Testing-and-Deployment-Scripts/blob/main/Other%20Scripts/get_marketing_model_name.sh) to name our computers; the [computer name field](https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L1957) in the public version of SYM is provided as a courtesy.)

**Comment by midiman1000** [comment]
Many thx!!
