### ISSUE TITLE
Feature Request:  Add Email Address and Realname to Recon Options

### ISSUE THREAD

**Issue by brianhm** [dan-snelson/Setup-Your-Mac#52]
Please add emailaddress and realname under reconOptions.  These can be YOYO :-)

Here are the recon command lines:
https://community.jamf.com/t5/jamf-pro/recon-command-line/m-p/14992

**Comment by rougegoat** [comment]
Looking at the `realname` and `email` flags, it should be easy enough to add this.  That said, wouldn't this information be pulled in from the directory service already once the username is set?

**Comment by brianhm** [comment]
We don't use LDAP in our environment, so we ask for it during enrollment with our DEP Notify setup currently.

**Comment by dan-snelson** [comment]
Thanks for keeping an eye on these, @rougegoat; I've invited @brianhm to submit a PR for this.

(If you don't have the cycles, @brianhm, please just let us know with an update here.)

**Comment by dan-snelson** [comment]
FYI only; no action required.

I'm planning to add this to SYM `1.12.0`.

**Comment by brianhm** [comment]
Yes, will do!  When do you need me to validate by @dan-snelson ?

**Comment by dan-snelson** [comment]
Thanks, @brianhm.

No huge rush … How about a week to 10 days?

**Comment by brianhm** [comment]
You have my seal of approval :-)  I verified fully today and have cut our script over in production!

**Comment by dan-snelson** [comment]
Addressed in [Setup Your Mac `1.12.0`](https://github.com/dan-snelson/Setup-Your-Mac/releases/tag/v1.12.0).
