### ISSUE TITLE
SYM `1.10.0`: Updating `title` instead of `bannertitle`

### ISSUE THREAD

**Issue by dan-snelson** [dan-snelson/Setup-Your-Mac#54]
**Describe the bug**
[Line 1572](https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#LL1572C66-L1572C98) currently updates `title`, but should most likely be updating `bannertitle`.

Thanks for the report, Brian Klotz!

**Comment by dan-snelson** [comment]
Steps to reproduce (?)

In one Terminal window, issue the following commands:

```
rm -v /var/tmp/dialog.log

dialog --infotext --moveable --bannerimage https://img.freepik.com/free-photo/dramatic-white-clouds-blue-sky-from-airplane-window-view-colorful-sunset-cloudscape-background_90220-1208.jpg --bannertitle "An Important Message"
```
<img width="932" alt="Screenshot 2023-05-09 at 5 04 11 PM" src="https://github.com/dan-snelson/Setup-Your-Mac/assets/24623109/9df1b138-19fb-47a2-b8df-b2da1f4168e3">

In a second Terminal window, issue the following commands:

```
echo "bannertitle: Updated Banner Title" >> /var/tmp/dialog.log
# Observe no change

echo "message: Updated message" >> /var/tmp/dialog.log
# Observe the message is updated
```

<img width="932" alt="Screenshot 2023-05-09 at 5 08 26 PM" src="https://github.com/dan-snelson/Setup-Your-Mac/assets/24623109/50a81e11-ef59-4dbf-b24d-9d3713e81f1d">

```
echo "title: Updated Title" >> /var/tmp/dialog.log
# Observe the `bannertitle` is updated

echo "bannertitle: Updated Banner Title" >> /var/tmp/dialog.log
# Observe no change
```

<img width="932" alt="Screenshot 2023-05-09 at 5 08 42 PM" src="https://github.com/dan-snelson/Setup-Your-Mac/assets/24623109/955a5ed8-93f6-45cf-806d-bd9234591f82">

```
echo "title: Updated Title 2" >> /var/tmp/dialog.log
# Observe the `bannertitle` is updated
```

<img width="932" alt="Screenshot 2023-05-09 at 5 09 03 PM" src="https://github.com/dan-snelson/Setup-Your-Mac/assets/24623109/db85e6ba-ffe7-4ae8-8fa7-8f71c680e7db">

**Comment by dan-snelson** [comment]
After counseling with Bart Reardon, this above behavior is "working as designed."

(Perhaps I'm looking at the wrong line in SYM.)

**Comment by dan-snelson** [comment]
See [Bart's response](https://macadmins.slack.com/archives/C04FRRN3281/p1683677967001999?thread_ts=1683640816.407319&cid=C04FRRN3281).

**Comment by brianhm** [comment]
I'm not sure that Bart is fully understanding what the issue is.  And this also applies to any of the areas where "title" is used in the "Finalise User Experience" block of code.  The issue is that if you use the "title" tag it does not behave the same way as the "bannertitle" tag.  If you use "title" and put \n characters in for a line break, they display as plain text and not as line breaks.  If you use "bannertitle" and put the \n characters in, they display properly as line breaks.

**Comment by dan-snelson** [comment]
Thanks for the update, @brianhm.

**Comment by dan-snelson** [comment]
@brianhm:

As this is a swiftDialog-related issue, I'll close it as "not planned."

Thanks.
