### ISSUE TITLE
Additional Parameter to set $symConfiguration value

### ISSUE THREAD

**Issue by nunoidev** [dan-snelson/Setup-Your-Mac#58]
This would be useful if we have just one SYM script added to multiple policies that are scoped to each prestage as a dynamic group (in Jamf).

i.e. in Jamf, SYM script is added to a policy that targets Prestage A dynamic group & have say parameter 11 value "PrestageA". The idea is to load the JSON Policy that matches "PrestageA" in $symConfiguration.

If Parameter 11 is not provided, then can use the catch-all option, as usual.

Slack Discussion: https://macadmins.slack.com/archives/C04FRRN3281/p1683853147821699

**Comment by dan-snelson** [comment]
@nunoidev: Please test-drive [`1.11.0-b9`](https://github.com/dan-snelson/Setup-Your-Mac/releases/tag/v1.11.0-b9).

Thanks big bunches, @drtaru!

**Comment by dan-snelson** [comment]
Thanks, @nunoidev and @drtaru!
