### ISSUE TITLE
Feature Request: Document SYM “racing-stripes” and gotchas

### ISSUE THREAD

**Issue by dan-snelson** [dan-snelson/Setup-Your-Mac#6]
Not every Mac Admin is able to publicly document how they’ve implemented SYM in Production. 

Create a “racing-stripes” blog post to point Mac Admins to others’ documentation / tips-and-tricks from #setup-your-mac.

For example:
- `enrollmentComplete`

**Comment by dan-snelson** [comment]
Perhaps create a blog post when SYM users could submit **their** "racing-stripes" (with an option for anonymous submissions).

**Comment by dan-snelson** [comment]
Two words: Zoom Rooms

**Comment by dan-snelson** [comment]
Document how to **not** use Configurations:

> While I haven't tried it, if you deleted [Configuration](https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L412-L419), the [catch-all](https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L974-L1064) policyJSON _should_ be all you need to modify.

**Comment by drtaru** [comment]
I will work on documenting how I personally have implemented `EnrollmentComplete` next week.

**Comment by dan-snelson** [comment]
Thanks, Obi-@drtaru!

**Comment by dan-snelson** [comment]
[swiftDialog Pre-install](https://snelson.us/2023/03/swiftdialog-notifications/#A)

**Comment by robjschroeder** [comment]
I do have this for ADE + SYM: https://techitout.xyz/2023/03/11/automated-device-enrollment-and-setup-your-mac-version-1-8-1/

I need to create a post about my Zoom Room deployments...

Also, not sure if this is the correct place you want things like this... feel free to let me know!

**Comment by dan-snelson** [comment]
Yoda says: "Racing stripe No. `1`, Master @robjschroeder [has already authored](https://snelson.us/2023/03/setup-your-mac-1-8-0-via-swiftdialog/#prestage-enrollments) … hmmmm?"

**Comment by dan-snelson** [comment]
Create a screencast of how to **Copy "Info.plist" as Pathname**

**Comment by dan-snelson** [comment]
Document how to upgrade to the latest version of SYM

**Comment by dan-snelson** [comment]
**Gotcha:** Inaccessible images _may_ prevent `swiftDialog` from **actually** rendering otherwise valid code.

**Comment by dan-snelson** [comment]
Update [Harvest Self Service Icons](https://vimeo.com/772998915) screencast.

**Comment by robjschroeder** [comment]
I have create a small documentation on how to create a dynamically populated drop down list for the welcomeJSON screen. I've posted it here: https://techitout.xyz/2023/04/12/setup-your-mac-zoom-room-edition/ . In my use case I am populating a choice of buildings based on the user's country.

**Comment by dan-snelson** [comment]
https://snelson.us/2022/06/pausing-initial-jamf-pro-inventory-collection/

**Comment by dan-snelson** [comment]
Document — if possible — how to **resume** a running SYM script if one purposely quit via `quitkey`.

**Comment by brianhm** [comment]
> Document — if possible — how to **resume** a running SYM script if one purposely quit via `quitkey`.
> 
> > jason folsom
> > [3 minutes ago](https://macadmins.slack.com/archives/C04FRRN3281/p1683749227684179?thread_ts=1683744757.253969&cid=C04FRRN3281)
> > If I quit the active dialog the script still runs in the background, is there any way to restore the active dialog or is just toast until the script quits?
> 
> > Dan K. Snelson
> > 💬  [1 minute ago](https://macadmins.slack.com/archives/C04FRRN3281/p1683749319125169?thread_ts=1683744757.253969&cid=C04FRRN3281)
> > Never tried, Jason.
> > (I suppose, if you launched dialog with `--commandfile`  that might work.)

Likewise, if the Swift Dialog quits or crashes, could there be some sort of detection routine that automatically relaunches it and reconnects to the current script execution process?

**Comment by dan-snelson** [comment]
> Likewise, if the Swift Dialog quits or crashes, could there be some sort of detection routine that automatically relaunches it and reconnects to the current script execution process?

Don't know that I've ever observed swiftDialog **crash**, @brianhm.

**Comment by dan-snelson** [comment]
Document using [Property List Writer](https://github.com/dan-snelson/Invitation-only-Betas/wiki/5.-Configuration:-Scripts#property-list-writer) to leave a client-side breadcrumb for successful SYM executions.

**Comment by dan-snelson** [comment]
Document how to control the "size" of various dialog "windows" (i.e., `height`).

- [welcomeVideo](https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L542)
- [welcomeJSON](https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L640)
- [Main SYM dialog](https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L712)
- [Failure dialog](https://github.com/dan-snelson/Setup-Your-Mac/blob/main/Setup-Your-Mac-via-Dialog.bash#L1315)

See also: [Custom Window Sizes](https://github.com/bartreardon/swiftDialog/wiki/Window-Size-and-Behaviour#custom-window-sizes) (test `%`  for height.)

**Comment by dan-snelson** [comment]
JNUC 2023: [Setup Your Mac: Racing Stripes, Gotchas and "One More Thing" [1024]](https://reg.jamf.com/flow/jamf/jnuc2023/home23/page/sessioncatalog/session/1677859236234001uTmx)
