### ISSUE TITLE
Feature Request: Test the network speed/stability when you run SYM

### ISSUE THREAD

**Issue by DevliegereM** [dan-snelson/Setup-Your-Mac#7]
> **Note:** While all requests are welcome, finding available cycles to custom-code a feature we won't use in our production environment is always challenging.

**Is your feature request related to a problem? Please describe.**
No, not a problem

**Describe the solution you'd like**
Depending on the score you can define which enrolment needs to happen? (basic/recommended/complete). You could even go as far as to let the admins decide what defines a good score (download speed/upload speed/network range/...) and have that defined inside SYM.

**Describe alternatives you've considered**
Running networkQuality to determine the speed and get the value from the result. 
Running speedtest-cli, but that depends on brew already being installed (more overhead)

**Additional context**
No, just an idea that popped up in my head when playing with 1.8.0.

**Comment by dan-snelson** [comment]
Thanks for the FR, @DevliegereM!

[A trio of networkQuality EAs](https://snelson.us/2022/08/a-trio-of-networkquality-eas/)

This might be too much overhead, but what if we looked at “Download Responsiveness” and `.PKG` size and then provided a rough estimate of the additional time required for any Configuration beyond “Required” ?

(Probably add yet another `case` statement with filesize estimates for each Configuration.)

**Comment by dan-snelson** [comment]
@DevliegereM:

Please test-drive [1.10.0-rc3](https://github.com/dan-snelson/Setup-Your-Mac/blob/development/Setup-Your-Mac-via-Dialog.bash):

## 1.10.0
### Release Date TBD
- :new: **Configuration Download Estimate** (Addresses [Issue No. 7]((https://github.com/dan-snelson/Setup-Your-Mac/issues/7)); thanks for the idea, @DevliegereM; heavy-lifting provided by @bartreardon!)
  - Manually set `configurationDownloadEstimation` within the script to `true` to enable
  - Specify an arbitrary value for `correctionCoefficient` (i.e., a "fudge factor" to help estimates match reality)
  - Calculate total file size (in MB) for each Configuration, then populate:
    - `configurationOneSize`
    - `configurationTwoSize`
    - `configurationThreeSize`

**Comment by DevliegereM** [comment]
Tested it and it works flawlessly if you use any of the three configurations. 
In production however we only use the catch-all since we deliver our macbooks to only have the basic of security tools and whatever department ends up using it they have their own follow up to do. 
It would be nice to have an estimated time left in the policy screen :)

**Comment by dan-snelson** [comment]
Excellent feedback, @DevliegereM. 

I’ll take a look.

**Comment by dan-snelson** [comment]
Thanks, @DevliegereM!
