### ISSUE TITLE
Bottom window cut off

### ISSUE THREAD

**Issue by dletkeman** [dan-snelson/Setup-Your-Mac#70]
Bottom window cut off with 13-inch Retina MacBook Pro (Late 2013) running Big Sur (macOS 11.7.5):

![bottom-cut-off](https://github.com/dan-snelson/Setup-Your-Mac/assets/51681386/ce59f674-5c7d-4a77-8b94-1bf6263e15c5)

I tried to eliminate some text in order to fit this in but it only left white space before the Computer Name selection.

This was run from Jamf Pro as a self serve policy.

When I hooked up the computer to external monitor and re-ran the policy it displayed the entire window.

I would expect the entire window to display on any version of Mac with Big Sur or beyond.

Running 1.11.0 script with basic modifications which can mostly be seen.  No major modifications to base script.

How can I eliminate the white space in order to ensure everything fits?  Or what can I do to ensure this issue doesn't happen on all computers?

**Comment by dan-snelson** [comment]
@dletkeman Please see the following:
https://github.com/dan-snelson/Setup-Your-Mac/issues/6#issuecomment-1578918385
