### ISSUE TITLE
Add scope for setups that do not open Self Service on enrolment to SYM cases that handle completionAction

### ISSUE THREAD

**Issue by master-vodawagner** [dan-snelson/Setup-Your-Mac#71]
> Before submitting a **Setup Your Mac** bug report, please review the [open swiftDialog issues](https://github.com/bartreardon/swiftDialog/issues) to help determine the source of the issue.

**Describe the bug**
Currently SYM has a list of cases for completionAction (In my case Restart-Attended), SYM when actioning the case looks to kill the Self Service process and waits for that to complete, however my company and others I;m sure are not launching Self Service during setup and I believe this is causing a hung state where devices are not triggering the restart due to no process running for Self Service and the wait command is causing SYM to become stale

**To Reproduce**
Uncheck Launch Self Service when done under Jamf Pro > Settings >Global > User-initiated enrollment
Run through SYM
 
**Expected behavior**
Device to process a restart no matter if Self Service is running or not

**Code/log output**
The Self service process is not running

**Screenshots**
NA

**Environment (please complete the following information):**
 - OS version (i.e., 13.1): 13.4
 - Script version (i.e., 1.6.0): 1.11.0

**Additional context**

**Comment by dan-snelson** [comment]
Thanks, @master-vodawagner; I think I've replicated this behavior in our Jamf Cloud Beta instance.

I'll take a look.

**Comment by dan-snelson** [comment]
@master-vodawagner:

In a single test, this is resolved in [`1.12.0-b6`](https://github.com/dan-snelson/Setup-Your-Mac/blob/1.12.0/Setup-Your-Mac-via-Dialog.bash#L2058) by using a _different_ one-liner (which is already detailed in **[I. Troubleshooting](https://snelson.us/2023/05/setup-your-mac-1-10-0-via-swiftdialog/#I) > 6. Various Restart Completion Actions not Working as Expected**.)

**Comment by dan-snelson** [comment]
@master-vodawagner:

Please see: **I. Troubleshooting > 6. Various Restart Completion Actions not Working as Expected**.
