### ISSUE TITLE
Overlay icon issues 

### ISSUE THREAD

**Issue by mani2care** [dan-snelson/Setup-Your-Mac#73]
Hi Dan, I am successfully upgraded my SYM to 1.11.0 find the attached snap however i noticed one small issue overlay icon at the end its not sowing and it’s till inventory update overlay icon showing me after end of screen its not showing and  i tried with 1.11.0 & 1.12.0-b6 with swiftdialog 2.2.1 still the same issues.
![IMG_6036](https://github.com/dan-snelson/Setup-Your-Mac/assets/52978899/f2413cad-2a88-4817-b4f4-37b9ae8cb119)
![IMG_6035](https://github.com/dan-snelson/Setup-Your-Mac/assets/52978899/d0e68384-1104-4b35-b52f-fdb5b8aaa2f8)

**Comment by dan-snelson** [comment]
@mani2care:

Please test-drive [`1.12.0-b7`](https://github.com/dan-snelson/Setup-Your-Mac/blob/1.12.0/Setup-Your-Mac-via-Dialog.bash).

Thanks.

**Comment by mani2care** [comment]
Looks good now thanks dan.

<img width="666" alt="image" src="https://github.com/dan-snelson/Setup-Your-Mac/assets/52978899/1885419c-2f56-4802-92ee-7f92e2fd2c75">

**Comment by dan-snelson** [comment]
Addressed in [Setup Your Mac `1.12.0`](https://github.com/dan-snelson/Setup-Your-Mac/releases/tag/v1.12.0).
