### ISSUE TITLE
Feature Request: Add "Required" options to User Input Fields

### ISSUE THREAD

**Issue by brianhm** [dan-snelson/Setup-Your-Mac#75]
- Allow for SYM dialog to require that users input something into the text input fields, like the newly added Email Address, using some sort of "required" mechanism.  Currently, it appears as if someone can continue with the "Email Address" field not having any data in it for example.
- For the email address field in particular, add some sort of verification that it looks like an email address.

**Comment by dan-snelson** [comment]
Addressed in `1.12.0-rc2` (sans _actual_ regex).

**Comment by brianhm** [comment]
Wow!

**Comment by brianhm** [comment]
Will test this now

**Comment by brianhm** [comment]
@dan-snelson Thanks so much for the quick response on this!  Verified that Email Address field is required by default.

**Comment by dan-snelson** [comment]
Addressed in [Setup Your Mac `1.12.0`](https://github.com/dan-snelson/Setup-Your-Mac/releases/tag/v1.12.0).
