### ISSUE TITLE
Feature Request:  Add "preFillRealName" Option

### ISSUE THREAD

**Issue by brianhm** [dan-snelson/Setup-Your-Mac#76]
There is currently a prefillUserName option (Line 68), but not an equivalent for prefillRealName.  Please add this.

**Comment by dan-snelson** [comment]
Addressed in `1.12.0-rc2`.

**Comment by brianhm** [comment]
Amazing!!

**Comment by brianhm** [comment]
Worked great!  Thanks, @dan-snelson

**Comment by dan-snelson** [comment]
Addressed in [Setup Your Mac `1.12.0`](https://github.com/dan-snelson/Setup-Your-Mac/releases/tag/v1.12.0).
