### ISSUE TITLE
SYM in case failed to install any application or policies retry’s request

### ISSUE THREAD

**Issue by mani2care** [dan-snelson/Setup-Your-Mac#8]
SYM in case failed to install any application or policies retry’s feature is required using launch agent launch daemon macos at next reboot it will start automatically installing again.

https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html

**Comment by dan-snelson** [comment]
@mani2care:

SYM is just “window dressing” for Jamf Pro Polices. 

If the polices fail to execute, there’s most likely a networking issue between the client and server.
