### ISSUE TITLE
Custom SYM Screen/Panel

### ISSUE THREAD

**Issue by beatlemike** [dan-snelson/Setup-Your-Mac#87]
**Is your feature request related to a problem? Please describe.**
This would hopefully help from having to code features not necessary to the primary mission of your organization.

**Describe the solution you'd like**
There  would be an ability to turn on a custom screen before the initial welcome to allow other SYM users to run their own swiftdialog code, additional video, slideshows, custom user input, or in my case the ability to send site information while still using the branding and look and feel of the SYM script as a whole.

**Describe alternatives you've considered**
Currently I run a separate script at first login that does what I need and then calls SYM.

**Comment by Honestpuck** [comment]
Can I vote against this. The script already has a number of features that add some complexity, we don't need more. As `beatlemike` says you can get the same result from running a script before calling SYM.

**Comment by bartreardon** [comment]
I'd agree with @Honestpuck - sym is sym and just a part of your overall workflow. Adding an extra screen to show random stuff is just as easy as appropriating the settings that sym uses and making your own dialog that does what you want it to do (which is kind of the point of swiftDialog actually - pop up random messages in peoples faces with whatever desired configuration you want). Coding that type of thing into a "fill in the blanks" pre-sym popup will be just as much effort than just writing the  popup yourself anyway.

**Comment by beatlemike** [comment]
Well clearly more people are against the idea than for it. I can admit defeat, it was just a wild hare of an idea to try and eliminate one extra policy at first login to go wrong. Doesn't have to be done.

**Comment by dan-snelson** [comment]
Thanks, @beatlemike; closing as "not planned."
